"""Noms des variables du modele, en francais.

Ce module ne contient QUE des libelles et la fonction qui les cherche. Il
n'importe rien de lourd, et c'est volontaire : l'API a besoin des libelles
pour motiver ses decisions, pas de matplotlib pour tracer des graphiques.

Le decoupage vient d'un incident. Les libelles vivaient dans expliquer.py, qui
importe matplotlib au chargement. L'image Docker de l'API, qui n'installe pas
matplotlib, refusait donc de demarrer. Une donnee partagee par deux usages ne
doit pas etre prisonniere du plus lourd des deux.

EXIGENCE C-5. Les 223 variables du modele ont un libelle. Le script
expliquer.py echoue s'il en manque une, et la route /sante de l'API le
verifie a chaque appel : un demandeur ne doit jamais recevoir un motif de
refus ecrit en nom de colonne.
"""

# Libelles lisibles pour les variables les plus frequentes. Un demandeur ne
# comprend pas "RATIO_ANNUITE_REVENU" ; il comprend "taux d'effort mensuel".
#
# C'est la regle F4 du plan de features : toute variable doit etre explicable a
# un client. Les variables absentes de cette table gardent leur nom technique —
# et ce sont celles qu'il faudra traduire avant la mise en production.
LIBELLES = {
    "RATIO_ANNUITE_REVENU": "taux d'effort mensuel",
    "RATIO_CREDIT_REVENU": "montant emprunte rapporte au revenu",
    "RATIO_ANNUITE_CREDIT": "durée implicite du pret",
    "RATIO_CREDIT_BIEN": "part financée du bien",
    "REVENU_PAR_PERSONNE": "revenu par personne du foyer",
    "RATIO_ANCIENNETE": "stabilite professionnelle",
    "NB_DOCUMENTS": "complétude du dossier",
    "AMT_CREDIT": "montant du crédit demandé",
    "AMT_ANNUITY": "mensualité",
    "AMT_INCOME_TOTAL": "revenu déclaré",
    "DAYS_EMPLOYED": "ancienneté dans l'emploi",
    "DAYS_REGISTRATION": "ancienneté du dossier",
    "ORGANIZATION_TYPE": "secteur d'activité de l'employeur",
    "OCCUPATION_TYPE": "catégorie professionnelle",
    "NAME_EDUCATION_TYPE": "niveau d'études",
    "NAME_INCOME_TYPE": "type de revenu",
    "EXT_SOURCE_1": "score externe n1",
    "EXT_SOURCE_2": "score externe n2",
    "EXT_SOURCE_3": "score externe n3",
    "INSTAL_RETARD_JOURS_MEAN": "retard moyen sur les échéances passees",
    "INSTAL_RETARD_JOURS_MAX": "retard le plus important constate",
    "INSTAL_RETARD_MAX_12M": "retard maximal sur les douze derniers mois",
    "INSTAL_PART_RETARDS": "part des échéances payées en retard",
    "INSTAL_TAUX_PAIEMENT_MEAN": "part des échéances effectivement reglees",
    "INSTAL_NB_ECHEANCES": "nombre d'échéances dans l'historique",
    "PREV_NB_DEMANDES": "nombre de demandes antérieures",
    "PREV_PART_REFUSEES": "part de demandes antérieures refusées",
    "PREV_PART_ACCORDEE_MEAN": "part du montant accorde par le passé",
    "BUREAU_NB_ACTIFS": "crédits en cours chez d'autres établissements",
    "BUREAU_DETTE_SUM": "dette totale chez d'autres établissements",
    "BUREAU_TAUX_UTILISATION": "utilisation des plafonds accordés ailleurs",
    "BUREAU_JOURS_CREDIT_RECENT": "ancienneté du dernier crédit externe",
    "BUREAU_NB_AVEC_IMPAYE": "crédits externes en impayé",
    "POS_DPD_MAX": "retard maximal sur les crédits en cours",
    "POS_PART_MOIS_RETARD": "part de mois en retard",
    "CC_TAUX_UTILISATION_MEAN": "utilisation moyenne du plafond de carte",
    "CC_TAUX_UTILISATION_MAX": "utilisation maximale du plafond de carte",
    "INSTAL_RESTE_DU": "montant restant dû sur les crédits antérieurs",
    "POS_MENSUALITES_RESTANTES": "mensualités restant a payer",
    "INSTAL_RETARD_JOURS_SUM": "cumul des jours de retard",
    "INSTAL_NB_RETARDS": "nombre d'échéances payées en retard",
    "INSTAL_NB_JAMAIS_PAYEES": "échéances jamais payées",
    "BUREAU_NB_CREDITS": "nombre de crédits chez d'autres établissements",
    "BUREAU_PLAFOND_SUM": "plafonds accordés par d'autres établissements",
    "PREV_AMT_CREDIT_MEAN": "montant moyen des crédits antérieurs",
    "POS_NB_ACTIFS": "crédits en cours",
    "CC_SOLDE_MEAN": "solde moyen de la carte de crédit",

    # Ajoutes le 31/08/2026 : ces 71 variables apparaissaient dans les cinq
    # motifs d'au moins un dossier sur les 5 000 examines. Sans libelle, un
    # demandeur aurait recu son motif de refus en jargon technique.
    "AMT_GOODS_PRICE": "prix du bien financé",
    "AMT_REQ_CREDIT_BUREAU_WEEK": "interrogations du bureau de crédit dans la semaine",
    "CNT_FAM_MEMBERS": "nombre de personnes dans le foyer",
    "DAYS_ID_PUBLISH": "ancienneté de la pièce d'identité",
    "DAYS_LAST_PHONE_CHANGE": "ancienneté du dernier changement de téléphone",
    "DEF_30_CNT_SOCIAL_CIRCLE": "proches ayant eu 30 jours de retard",
    "DEF_60_CNT_SOCIAL_CIRCLE": "proches ayant eu 60 jours de retard",
    "FLAG_DOCUMENT_3": "fourniture du document 3",
    "FLAG_WORK_PHONE": "téléphone professionnel fourni",
    "NAME_HOUSING_TYPE": "type de logement",
    "NAME_TYPE_SUITE": "accompagnant lors de la demandé",
    "OWN_CAR_AGE": "âge du véhicule",
    "REGION_POPULATION_RELATIVE": "densité de population de la région",
    "REGION_RATING_CLIENT_W_CITY": "note de la région de résidence",
    "REG_CITY_NOT_LIVE_CITY": "adresse déclarée différente de la résidence",
    "WEEKDAY_APPR_PROCESS_START": "jour de la semaine de la demandé",
    "APARTMENTS_MEDI": "surface des appartements de l'immeuble (médiane)",
    "APARTMENTS_MODE": "surface des appartements de l'immeuble (mode)",
    "BASEMENTAREA_MODE": "surface des sous-sols de l'immeuble",
    "COMMONAREA_AVG": "surface des parties communes",
    "ELEVATORS_MEDI": "nombre d'ascenseurs de l'immeuble",
    "LIVINGAREA_MEDI": "surface habitable",
    "NONLIVINGAPARTMENTS_MEDI": "locaux non habitables de l'immeuble (médiane)",
    "NONLIVINGAPARTMENTS_MODE": "locaux non habitables de l'immeuble (mode)",
    "TOTALAREA_MODE": "surface totale de l'immeuble",
    "YEARS_BEGINEXPLUATATION_MODE": "année de mise en service de l'immeuble",
    "BB_NB_MOIS": "mois d'historique détaillé des crédits extérieurs",
    "BB_PART_CLOS": "part des mois ou le crédit extérieur etait solde",
    "BUREAU_ANNUITE_SUM": "total des mensualités chez d'autres établissements",
    "BUREAU_DETTE_MAX": "dette la plus elevee chez un autre établissement",
    "BUREAU_DETTE_MEAN": "dette moyenne chez les autres établissements",
    "BUREAU_DUREE_HISTORIQUE_JOURS": "ancienneté de l'historique extérieur",
    "BUREAU_IMPAYE_HISTORIQUE_MAX": "impayé le plus élevé de tout l'historique extérieur",
    "BUREAU_IMPAYE_MAX": "impayé courant le plus élevé",
    "BUREAU_IMPAYE_SUM": "total des impayés courants",
    "BUREAU_JOURS_FIN_MAX": "échéance la plus lointaine des crédits extérieurs",
    "BUREAU_JOURS_MAJ_RECENTE": "ancienneté de la dernière mise à jour du bureau",
    "BUREAU_PART_CLOS": "part des crédits extérieurs déjà soldés",
    "BUREAU_PART_VENDUS": "part des crédits extérieurs cédés a un tiers",
    "BUREAU_PLAFOND_MAX": "plafond le plus élevé accorde ailleurs",
    "CC_MONTANT_RETRAITS_ESPECES": "montant retire en espèces sur la carte",
    "CC_NB_MOIS": "mois d'historique de carte de crédit",
    "CC_NB_OPERATIONS": "nombre d'opérations sur la carte",
    "CC_NB_RETRAITS_ESPECES": "nombre de retraits en espèces",
    "CC_PART_RETRAITS_ESPECES": "part des retraits en espèces dans l'usage de la carte",
    "CC_PLAFOND_SUM": "total des plafonds de carte",
    "CC_TAUX_UTILISATION_12M": "taux d'utilisation de la carte sur douze mois",
    "INSTAL_MONTANT_DU_SUM": "total dû à l'échéancier",
    "INSTAL_MONTANT_PAYE_SUM": "total effectivement paye",
    "INSTAL_NB_CREDITS": "nombre de crédits antérieurs avec échéancier",
    "INSTAL_NB_ECHEANCES_12M": "échéances sur les douze derniers mois",
    "INSTAL_RETARD_JOURS_STD": "irregularite des retards de paiement",
    "POS_DERNIER_MOIS": "ancienneté du dernier point de situation",
    "POS_DPD_DEF_MAX": "retard grave maximal constate",
    "POS_DPD_DEF_MEAN": "retard grave moyen",
    "POS_NB_MOIS": "mois d'historique de crédit a la consommation",
    "POS_NB_TERMINES": "crédits a la consommation menés a terme",
    "POS_PART_MOIS_RETARD_GRAVE": "part des mois passes en retard grave",
    "PREV_AMT_ANNUITY_MAX": "mensualité la plus elevee des demandes antérieures",
    "PREV_AMT_ANNUITY_MEAN": "mensualité moyenne des demandes antérieures",
    "PREV_AMT_DOWN_PAYMENT_MEAN": "apport moyen des demandes antérieures",
    "PREV_CNT_PAYMENT_MAX": "durée la plus longue accordée par le passé",
    "PREV_CNT_PAYMENT_MEAN": "durée moyenne des crédits antérieurs",
    "PREV_JOURS_DERNIERE_DEMANDE": "ancienneté de la dernière demandé",
    "PREV_JOURS_PREMIERE_DEMANDE": "ancienneté de la première demandé",
    "PREV_NB_REFUSEES": "nombre de demandes antérieures refusées",
    "PREV_PART_ACCEPTEES": "part des demandes antérieures acceptées",
    "PREV_PART_ACCORDEE_MIN": "part la plus faible du montant demandé qui a été accordée",
    "PREV_PART_CONSO": "part des crédits a la consommation dans l'historique",
    "PREV_PART_RENOUVELABLE": "part des crédits renouvelables dans l'historique",
    "PREV_RATE_DOWN_PAYMENT_MEAN": "taux d'apport moyen des demandes antérieures",

    # Completes apres mesure sur les 61 503 dossiers de test : ces 40
    # variables atteignaient le haut du classement d'au moins un dossier.
    "AMT_REQ_CREDIT_BUREAU_QRT": "interrogations du bureau de crédit dans le trimestre",
    "HOUR_APPR_PROCESS_START": "heure de dépôt de la demandé",
    "OBS_30_CNT_SOCIAL_CIRCLE": "proches observés a 30 jours de retard",
    "REGION_RATING_CLIENT": "note de la région du demandeur",
    "APARTMENTS_AVG": "surface des appartements de l'immeuble (moyenne)",
    "BASEMENTAREA_AVG": "surface des sous-sols (moyenne)",
    "BASEMENTAREA_MEDI": "surface des sous-sols (médiane)",
    "COMMONAREA_MEDI": "surface des parties communes (médiane)",
    "ELEVATORS_MODE": "nombre d'ascenseurs (mode)",
    "ENTRANCES_AVG": "nombre d'entrées de l'immeuble (moyenne)",
    "ENTRANCES_MEDI": "nombre d'entrées de l'immeuble (médiane)",
    "ENTRANCES_MODE": "nombre d'entrées de l'immeuble (mode)",
    "FLOORSMAX_MEDI": "nombre d'étages de l'immeuble (médiane)",
    "FLOORSMIN_MEDI": "nombre minimal d'étages (médiane)",
    "FLOORSMIN_MODE": "nombre minimal d'étages (mode)",
    "LANDAREA_AVG": "surface du terrain (moyenne)",
    "LANDAREA_MODE": "surface du terrain (mode)",
    "LIVINGAPARTMENTS_AVG": "logements habitables de l'immeuble (moyenne)",
    "LIVINGAPARTMENTS_MODE": "logements habitables de l'immeuble (mode)",
    "LIVINGAREA_AVG": "surface habitable (moyenne)",
    "NONLIVINGAPARTMENTS_AVG": "locaux non habitables (moyenne)",
    "NONLIVINGAREA_AVG": "surface non habitable (moyenne)",
    "NONLIVINGAREA_MEDI": "surface non habitable (médiane)",
    "WALLSMATERIAL_MODE": "matériau des murs de l'immeuble",
    "YEARS_BEGINEXPLUATATION_MEDI": "année de mise en service (médiane)",
    "YEARS_BUILD_AVG": "année de construction de l'immeuble",
    "BB_NB_MOIS_RETARD": "mois de retard sur les crédits extérieurs",
    "BB_PART_MOIS_RETARD": "part des mois passes en retard a l'extérieur",
    "BUREAU_ANNUITE_MEAN": "mensualité moyenne chez les autres établissements",
    "BUREAU_JOURS_CREDIT_ANCIEN": "ancienneté du plus vieux crédit extérieur",
    "BUREAU_PART_ACTIFS": "part des crédits extérieurs encore actifs",
    "POS_DPD_MEAN": "retard moyen sur les crédits a la consommation",
    "POS_NB_CREDITS": "nombre de crédits a la consommation suivis",
    "PREV_AMT_APPLICATION_MAX": "montant le plus élevé demandé par le passé",
    "PREV_AMT_APPLICATION_MEAN": "montant moyen demandé par le passé",
    "PREV_AMT_CREDIT_MAX": "montant le plus élevé accorde par le passé",
    "PREV_DUREE_RELATION_JOURS": "ancienneté de la relation avec l'établissement",
    "PREV_PART_ANNULEES": "part des demandes antérieures annulees",
    "PREV_PART_NON_UTILISEES": "part des crédits accordés mais non utilises",
    "PREV_PART_TRESORERIE": "part des crédits de tresorerie dans l'historique",

    # Completes le 02/09/2026 : les 65 dernieres. La mesure precedente ne
    # couvrait que les variables VUES dans un top-5 sur le jeu de test — un
    # nouveau demandeur peut en faire remonter une autre. Toutes les
    # variables du modele ont desormais un libelle, la garantie est totale
    # et non plus statistique.
    "NAME_CONTRACT_TYPE": "type de contrat demandé",
    "FLAG_OWN_CAR": "possède un véhicule",
    "FLAG_OWN_REALTY": "propriétaire d'un bien immobilier",
    "CNT_CHILDREN": "nombre d'enfants a charge",
    "FLAG_MOBIL": "téléphone mobile fourni",
    "FLAG_CONT_MOBILE": "mobile joignable",
    "FLAG_PHONE": "téléphone fixe fourni",
    "FLAG_EMAIL": "adresse électronique fournie",
    "REG_REGION_NOT_LIVE_REGION": "région déclarée différente de la région de résidence",
    "REG_REGION_NOT_WORK_REGION": "région déclarée différente de la région de travail",
    "LIVE_REGION_NOT_WORK_REGION": "résidence et travail dans deux regions",
    "REG_CITY_NOT_WORK_CITY": "ville déclarée différente de la ville de travail",
    "LIVE_CITY_NOT_WORK_CITY": "résidence et travail dans deux villes",
    "YEARS_BEGINEXPLUATATION_AVG": "année de mise en service (moyenne)",
    "ELEVATORS_AVG": "nombre d'ascenseurs (moyenne)",
    "FLOORSMAX_AVG": "nombre d'étages (moyenne)",
    "FLOORSMIN_AVG": "nombre minimal d'étages (moyenne)",
    "YEARS_BUILD_MODE": "année de construction (mode)",
    "YEARS_BUILD_MEDI": "année de construction (médiane)",
    "COMMONAREA_MODE": "surface des parties communes (mode)",
    "FLOORSMAX_MODE": "nombre d'étages (mode)",
    "LIVINGAREA_MODE": "surface habitable (mode)",
    "NONLIVINGAREA_MODE": "surface non habitable (mode)",
    "LANDAREA_MEDI": "surface du terrain (médiane)",
    "LIVINGAPARTMENTS_MEDI": "logements habitables de l'immeuble (médiane)",
    "FONDKAPREMONT_MODE": "régime de financement des travaux de l'immeuble",
    "HOUSETYPE_MODE": "type d'immeuble",
    "EMERGENCYSTATE_MODE": "immeuble déclaré en état d'urgence",
    "OBS_60_CNT_SOCIAL_CIRCLE": "proches observés a 60 jours de retard",
    "AMT_REQ_CREDIT_BUREAU_HOUR": "interrogations du bureau dans l'heure",
    "AMT_REQ_CREDIT_BUREAU_DAY": "interrogations du bureau dans la journée",
    "AMT_REQ_CREDIT_BUREAU_MON": "interrogations du bureau dans le mois",
    "AMT_REQ_CREDIT_BUREAU_YEAR": "interrogations du bureau dans l'année",
    "DAYS_EMPLOYED_ANORMAL": "absence d'emploi salarié déclaré",
    "INSTAL_PRESENT": "dispose d'un historique d'échéancier",
    "PREV_PRESENT": "a déjà depose une demandé",
    "POS_PRESENT": "dispose d'un historique de crédit a la consommation",
    "BUREAU_PRESENT": "connu d'autres établissements de crédit",
    "BB_PRESENT": "dispose d'un historique mensuel extérieur",
    "CC_PRESENT": "detient une carte de crédit",
    "INSTAL_TAUX_PAIEMENT_MIN": "plus faible taux de paiement d'une échéance",
    "PREV_AMT_CREDIT_SUM": "total des montants accordés par le passé",
    "PREV_AMT_GOODS_PRICE_MEAN": "prix moyen des biens finances par le passé",
    "PREV_PART_ASSUREES": "part des demandes antérieures avec assurance",
    "POS_NB_MOIS_RETARD": "mois de retard sur les crédits a la consommation",
    "POS_NB_MOIS_RETARD_GRAVE": "mois de retard grave sur les crédits a la consommation",
    "BUREAU_NB_TYPES": "nombre de types de crédits detenus ailleurs",
    "BUREAU_JOURS_IMPAYE_MAX": "durée maximale d'un impayé extérieur",
    "BUREAU_NB_PROLONGATIONS": "nombre de prolongations obtenues ailleurs",
    "BUREAU_NB_SANS_ECHEANCE": "crédits extérieurs sans échéance connue",
    "BUREAU_PART_IMPAYES": "part des crédits extérieurs en impayé",
    "BUREAU_PART_CONSO": "part des crédits a la consommation a l'extérieur",
    "BUREAU_PART_CARTE": "part des cartes de crédit a l'extérieur",
    "BB_NB_CREDITS": "crédits extérieurs suivis mois par mois",
    "BB_GRAVITE_MAX": "gravité maximale d'un retard extérieur",
    "BB_GRAVITE_MEAN": "gravité moyenne des retards extérieurs",
    "BB_PART_INCONNU": "part des mois sans information extérieure",
    "BB_DERNIER_MOIS": "ancienneté de la dernière information extérieure",
    "CC_NB_CARTES": "nombre de cartes de crédit detenues",
    "CC_PAIEMENT_MEAN": "paiement mensuel moyen sur la carte",
    "CC_DPD_MEAN": "retard moyen sur la carte",
    "CC_DPD_MAX": "retard maximal sur la carte",
    "CC_DPD_DEF_MAX": "retard grave maximal sur la carte",
    "CC_NB_MOIS_RETARD": "mois de retard sur la carte",
    "CC_TENDANCE_UTILISATION": "évolution de l'utilisation de la carte",
}


def libelle(variable):
    """Nom lisible d'une variable, ou son nom technique a defaut."""
    return LIBELLES.get(variable, variable)
